import type { JobVM, PrinterVM, ProjectVM } from "./types";

// In-memory demo data so the dashboards are navigable without a database.
// Mirrors the shape of the records produced by prisma/seed.ts.

export const MOCK_PROJECTS: ProjectVM[] = [
  {
    id: "prj_cosplay_helmet",
    title: "Casco Mandaloriano (cosplay)",
    category: "cosplay",
    status: "MODEL_REVIEW",
    clientName: "Giulia R.",
    designerName: "Marco — DesignLab",
    makerName: null,
    designPrice: 80,
    printPrice: null,
    material: "PLA",
    requiredX: 240,
    requiredY: 210,
    requiredZ: 290,
    qcStatus: "AWAITING_PHOTOS",
    qcDueAt: null,
    renderUrl: "/renders/helmet.png",
    qcPhotoUrls: [],
    updatedAt: "2026-05-24T10:00:00.000Z",
  },
  {
    id: "prj_boardgame_inserts",
    title: "Organizer per Gloomhaven",
    category: "boardgames",
    status: "PRINTING",
    clientName: "Luca B.",
    designerName: "Sara — MeepleWorks",
    makerName: "Andrea (Prusa MK4)",
    designPrice: 35,
    printPrice: 60,
    material: "PETG",
    requiredX: 180,
    requiredY: 180,
    requiredZ: 60,
    qcStatus: "AWAITING_PHOTOS",
    qcDueAt: null,
    renderUrl: "/renders/inserts.png",
    qcPhotoUrls: [],
    updatedAt: "2026-05-25T08:30:00.000Z",
  },
  {
    id: "prj_drone_arm",
    title: "Braccio drone FPV (ricambio)",
    category: "spare-parts",
    status: "QC_PENDING",
    clientName: "Davide P.",
    designerName: "Marco — DesignLab",
    makerName: "Elena (Bambu X1C)",
    designPrice: 20,
    printPrice: 25,
    material: "NYLON",
    requiredX: 120,
    requiredY: 60,
    requiredZ: 25,
    qcStatus: "AWAITING_APPROVAL",
    qcDueAt: "2026-05-27T09:00:00.000Z",
    renderUrl: "/renders/drone-arm.png",
    qcPhotoUrls: ["/qc/arm-1.jpg", "/qc/arm-2.jpg", "/qc/arm-3.jpg"],
    updatedAt: "2026-05-25T09:00:00.000Z",
  },
  {
    id: "prj_dragon_mini",
    title: "Miniatura Drago 75mm (resina)",
    category: "scale-models",
    status: "MATCHING",
    clientName: "Chiara M.",
    designerName: "Sara — MeepleWorks",
    makerName: null,
    designPrice: 15,
    printPrice: 30,
    material: "RESIN_STANDARD",
    requiredX: 70,
    requiredY: 55,
    requiredZ: 90,
    qcStatus: "AWAITING_PHOTOS",
    qcDueAt: null,
    renderUrl: "/renders/dragon.png",
    qcPhotoUrls: [],
    updatedAt: "2026-05-25T07:15:00.000Z",
  },
  {
    id: "prj_planter",
    title: "Vaso geometrico da esterno",
    category: "spare-parts",
    status: "COMPLETED",
    clientName: "Giulia R.",
    designerName: "Marco — DesignLab",
    makerName: "Andrea (Prusa MK4)",
    designPrice: 10,
    printPrice: 22,
    material: "PETG",
    requiredX: 150,
    requiredY: 150,
    requiredZ: 180,
    qcStatus: "AUTO_APPROVED",
    qcDueAt: null,
    renderUrl: "/renders/planter.png",
    qcPhotoUrls: ["/qc/planter-1.jpg", "/qc/planter-2.jpg", "/qc/planter-3.jpg"],
    updatedAt: "2026-05-20T16:40:00.000Z",
  },
];

export const MOCK_PRINTERS: PrinterVM[] = [
  {
    id: "ptr_prusa_mk4",
    name: "Prusa MK4",
    technology: "FDM",
    buildX: 250,
    buildY: 210,
    buildZ: 220,
    materials: ["PLA", "PETG", "ABS", "TPU"],
    status: "ACTIVE",
    octoprintConnected: true,
  },
  {
    id: "ptr_bambu_x1c",
    name: "Bambu Lab X1 Carbon",
    technology: "FDM",
    buildX: 256,
    buildY: 256,
    buildZ: 256,
    materials: ["PLA", "PETG", "ABS", "NYLON", "TPU"],
    status: "ACTIVE",
    octoprintConnected: false,
  },
  {
    id: "ptr_saturn",
    name: "Elegoo Saturn 3 (resina)",
    technology: "SLA",
    buildX: 219,
    buildY: 123,
    buildZ: 250,
    materials: ["RESIN_STANDARD", "RESIN_TOUGH", "RESIN_FLEXIBLE"],
    status: "BUSY",
    octoprintConnected: false,
  },
];

// Open jobs offered to makers — derived metadata only, never source files.
export const MOCK_JOBS: JobVM[] = [
  {
    id: "prj_dragon_mini",
    title: "Miniatura Drago 75mm (resina)",
    category: "scale-models",
    material: "RESIN_STANDARD",
    requiredX: 70,
    requiredY: 55,
    requiredZ: 90,
    volumeCm3: 41.2,
    printPrice: 30,
  },
  {
    id: "prj_cosplay_helmet",
    title: "Casco Mandaloriano (cosplay)",
    category: "cosplay",
    material: "PLA",
    requiredX: 240,
    requiredY: 210,
    requiredZ: 290,
    volumeCm3: 980.0,
    printPrice: 140,
  },
  {
    id: "prj_phone_stand",
    title: "Supporto telefono regolabile",
    category: "spare-parts",
    material: "PLA",
    requiredX: 110,
    requiredY: 90,
    requiredZ: 130,
    volumeCm3: 95.5,
    printPrice: 18,
  },
];
